### ISSUE TITLE
more issue

### ISSUE THREAD

**Issue by Panizghi** [jaxendutta/cs492-csam#6]
- [x] - update the name of the "logo"
- [x] - survey graph  
- [ ] - center video div 
- [x] - quiz page subtext under title 
- [x] fix the survey padding 
- [ ] host the website using github io

**Comment by albina-dev** [comment]
> * [x]  - update the name of the "logo"
> * [x]  - survey graph
> * [ ]  - center video div
> * [ ]  - quiz page subtext under title
> * [x]  fix the survey padding
> * [ ]  host the website using github io
> * [x]  add survey charts in quiz according to doc
